package ru.hmel.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import ru.hmel.model.ElectroEmployee;

import ru.hmel.service.ElectroEmployeeLocalServiceUtil;

/**
 * The extended model base implementation for the ElectroEmployee service. Represents a row in the &quot;store_ElectroEmployee&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ElectroEmployeeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ElectroEmployeeImpl
 * @see ru.hmel.model.ElectroEmployee
 * @generated
 */
public abstract class ElectroEmployeeBaseImpl extends ElectroEmployeeModelImpl
    implements ElectroEmployee {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a electro employee model instance should use the {@link ElectroEmployee} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            ElectroEmployeeLocalServiceUtil.addElectroEmployee(this);
        } else {
            ElectroEmployeeLocalServiceUtil.updateElectroEmployee(this);
        }
    }
}
