package ru.hmel.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import ru.hmel.model.ElectroType;

import ru.hmel.service.ElectroTypeLocalServiceUtil;

/**
 * The extended model base implementation for the ElectroType service. Represents a row in the &quot;store_ElectroType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ElectroTypeImpl}.
 * </p>
 *
 * @author Hmel Max
 * @see ElectroTypeImpl
 * @see ru.hmel.model.ElectroType
 * @generated
 */
public abstract class ElectroTypeBaseImpl extends ElectroTypeModelImpl
    implements ElectroType {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a electro type model instance should use the {@link ElectroType} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            ElectroTypeLocalServiceUtil.addElectroType(this);
        } else {
            ElectroTypeLocalServiceUtil.updateElectroType(this);
        }
    }
}
