package ru.hmel.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import ru.hmel.model.PositionType;

import ru.hmel.service.PositionTypeLocalServiceUtil;

/**
 * The extended model base implementation for the PositionType service. Represents a row in the &quot;store_PositionType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PositionTypeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PositionTypeImpl
 * @see ru.hmel.model.PositionType
 * @generated
 */
public abstract class PositionTypeBaseImpl extends PositionTypeModelImpl
    implements PositionType {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a position type model instance should use the {@link PositionType} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            PositionTypeLocalServiceUtil.addPositionType(this);
        } else {
            PositionTypeLocalServiceUtil.updatePositionType(this);
        }
    }
}
