package ru.hmel.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import ru.hmel.model.PurchaseType;
import ru.hmel.model.PurchaseTypeModel;
import ru.hmel.model.PurchaseTypeSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the PurchaseType service. Represents a row in the &quot;store_PurchaseType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link ru.hmel.model.PurchaseTypeModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PurchaseTypeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PurchaseTypeImpl
 * @see ru.hmel.model.PurchaseType
 * @see ru.hmel.model.PurchaseTypeModel
 * @generated
 */
@JSON(strict = true)
public class PurchaseTypeModelImpl extends BaseModelImpl<PurchaseType>
    implements PurchaseTypeModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a purchase type model instance should use the {@link ru.hmel.model.PurchaseType} interface instead.
     */
    public static final String TABLE_NAME = "store_PurchaseType";
    public static final Object[][] TABLE_COLUMNS = {
            { "uuid_", Types.VARCHAR },
            { "purchase_type_id", Types.BIGINT },
            { "name", Types.VARCHAR }
        };
    public static final String TABLE_SQL_CREATE = "create table store_PurchaseType (uuid_ VARCHAR(75) null,purchase_type_id LONG not null primary key,name VARCHAR(75) null)";
    public static final String TABLE_SQL_DROP = "drop table store_PurchaseType";
    public static final String ORDER_BY_JPQL = " ORDER BY purchaseType.purchase_type_id ASC";
    public static final String ORDER_BY_SQL = " ORDER BY store_PurchaseType.purchase_type_id ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.ru.hmel.model.PurchaseType"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.ru.hmel.model.PurchaseType"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.column.bitmask.enabled.ru.hmel.model.PurchaseType"),
            true);
    public static long UUID_COLUMN_BITMASK = 1L;
    public static long PURCHASE_TYPE_ID_COLUMN_BITMASK = 2L;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.ru.hmel.model.PurchaseType"));
    private static ClassLoader _classLoader = PurchaseType.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            PurchaseType.class
        };
    private String _uuid;
    private String _originalUuid;
    private long _purchase_type_id;
    private String _name;
    private long _columnBitmask;
    private PurchaseType _escapedModel;

    public PurchaseTypeModelImpl() {
    }

    /**
     * Converts the soap model instance into a normal model instance.
     *
     * @param soapModel the soap model instance to convert
     * @return the normal model instance
     */
    public static PurchaseType toModel(PurchaseTypeSoap soapModel) {
        if (soapModel == null) {
            return null;
        }

        PurchaseType model = new PurchaseTypeImpl();

        model.setUuid(soapModel.getUuid());
        model.setPurchase_type_id(soapModel.getPurchase_type_id());
        model.setName(soapModel.getName());

        return model;
    }

    /**
     * Converts the soap model instances into normal model instances.
     *
     * @param soapModels the soap model instances to convert
     * @return the normal model instances
     */
    public static List<PurchaseType> toModels(PurchaseTypeSoap[] soapModels) {
        if (soapModels == null) {
            return null;
        }

        List<PurchaseType> models = new ArrayList<PurchaseType>(soapModels.length);

        for (PurchaseTypeSoap soapModel : soapModels) {
            models.add(toModel(soapModel));
        }

        return models;
    }

    @Override
    public long getPrimaryKey() {
        return _purchase_type_id;
    }

    @Override
    public void setPrimaryKey(long primaryKey) {
        setPurchase_type_id(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _purchase_type_id;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    @Override
    public Class<?> getModelClass() {
        return PurchaseType.class;
    }

    @Override
    public String getModelClassName() {
        return PurchaseType.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("uuid", getUuid());
        attributes.put("purchase_type_id", getPurchase_type_id());
        attributes.put("name", getName());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        String uuid = (String) attributes.get("uuid");

        if (uuid != null) {
            setUuid(uuid);
        }

        Long purchase_type_id = (Long) attributes.get("purchase_type_id");

        if (purchase_type_id != null) {
            setPurchase_type_id(purchase_type_id);
        }

        String name = (String) attributes.get("name");

        if (name != null) {
            setName(name);
        }
    }

    @JSON
    @Override
    public String getUuid() {
        if (_uuid == null) {
            return StringPool.BLANK;
        } else {
            return _uuid;
        }
    }

    @Override
    public void setUuid(String uuid) {
        if (_originalUuid == null) {
            _originalUuid = _uuid;
        }

        _uuid = uuid;
    }

    public String getOriginalUuid() {
        return GetterUtil.getString(_originalUuid);
    }

    @JSON
    @Override
    public long getPurchase_type_id() {
        return _purchase_type_id;
    }

    @Override
    public void setPurchase_type_id(long purchase_type_id) {
        _purchase_type_id = purchase_type_id;
    }

    @JSON
    @Override
    public String getName() {
        if (_name == null) {
            return StringPool.BLANK;
        } else {
            return _name;
        }
    }

    @Override
    public void setName(String name) {
        _name = name;
    }

    public long getColumnBitmask() {
        return _columnBitmask;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
            PurchaseType.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public PurchaseType toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (PurchaseType) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        PurchaseTypeImpl purchaseTypeImpl = new PurchaseTypeImpl();

        purchaseTypeImpl.setUuid(getUuid());
        purchaseTypeImpl.setPurchase_type_id(getPurchase_type_id());
        purchaseTypeImpl.setName(getName());

        purchaseTypeImpl.resetOriginalValues();

        return purchaseTypeImpl;
    }

    @Override
    public int compareTo(PurchaseType purchaseType) {
        long primaryKey = purchaseType.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof PurchaseType)) {
            return false;
        }

        PurchaseType purchaseType = (PurchaseType) obj;

        long primaryKey = purchaseType.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
        PurchaseTypeModelImpl purchaseTypeModelImpl = this;

        purchaseTypeModelImpl._originalUuid = purchaseTypeModelImpl._uuid;

        purchaseTypeModelImpl._columnBitmask = 0;
    }

    @Override
    public CacheModel<PurchaseType> toCacheModel() {
        PurchaseTypeCacheModel purchaseTypeCacheModel = new PurchaseTypeCacheModel();

        purchaseTypeCacheModel.uuid = getUuid();

        String uuid = purchaseTypeCacheModel.uuid;

        if ((uuid != null) && (uuid.length() == 0)) {
            purchaseTypeCacheModel.uuid = null;
        }

        purchaseTypeCacheModel.purchase_type_id = getPurchase_type_id();

        purchaseTypeCacheModel.name = getName();

        String name = purchaseTypeCacheModel.name;

        if ((name != null) && (name.length() == 0)) {
            purchaseTypeCacheModel.name = null;
        }

        return purchaseTypeCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(7);

        sb.append("{uuid=");
        sb.append(getUuid());
        sb.append(", purchase_type_id=");
        sb.append(getPurchase_type_id());
        sb.append(", name=");
        sb.append(getName());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(13);

        sb.append("<model><model-name>");
        sb.append("ru.hmel.model.PurchaseType");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>uuid</column-name><column-value><![CDATA[");
        sb.append(getUuid());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>purchase_type_id</column-name><column-value><![CDATA[");
        sb.append(getPurchase_type_id());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>name</column-name><column-value><![CDATA[");
        sb.append(getName());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
