package ru.hmel.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import ru.hmel.model.PurchaseType;

import ru.hmel.service.PurchaseTypeLocalServiceUtil;

/**
 * The extended model base implementation for the PurchaseType service. Represents a row in the &quot;store_PurchaseType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PurchaseTypeImpl}.
 * </p>
 *
 * @author Hmel Max
 * @see PurchaseTypeImpl
 * @see ru.hmel.model.PurchaseType
 * @generated
 */
public abstract class PurchaseTypeBaseImpl extends PurchaseTypeModelImpl
    implements PurchaseType {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a purchase type model instance should use the {@link PurchaseType} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            PurchaseTypeLocalServiceUtil.addPurchaseType(this);
        } else {
            PurchaseTypeLocalServiceUtil.updatePurchaseType(this);
        }
    }
}
