package ru.hmel.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import ru.hmel.model.PositionType;
import ru.hmel.model.PositionTypeModel;
import ru.hmel.model.PositionTypeSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the PositionType service. Represents a row in the &quot;store_PositionType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link ru.hmel.model.PositionTypeModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PositionTypeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PositionTypeImpl
 * @see ru.hmel.model.PositionType
 * @see ru.hmel.model.PositionTypeModel
 * @generated
 */
@JSON(strict = true)
public class PositionTypeModelImpl extends BaseModelImpl<PositionType>
    implements PositionTypeModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a position type model instance should use the {@link ru.hmel.model.PositionType} interface instead.
     */
    public static final String TABLE_NAME = "store_PositionType";
    public static final Object[][] TABLE_COLUMNS = {
            { "uuid_", Types.VARCHAR },
            { "position_id", Types.BIGINT },
            { "name", Types.VARCHAR }
        };
    public static final String TABLE_SQL_CREATE = "create table store_PositionType (uuid_ VARCHAR(75) null,position_id LONG not null primary key,name VARCHAR(75) null)";
    public static final String TABLE_SQL_DROP = "drop table store_PositionType";
    public static final String ORDER_BY_JPQL = " ORDER BY positionType.position_id ASC";
    public static final String ORDER_BY_SQL = " ORDER BY store_PositionType.position_id ASC";
    public static final String DATA_SOURCE = "liferayDataSource";
    public static final String SESSION_FACTORY = "liferaySessionFactory";
    public static final String TX_MANAGER = "liferayTransactionManager";
    public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.entity.cache.enabled.ru.hmel.model.PositionType"),
            true);
    public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.finder.cache.enabled.ru.hmel.model.PositionType"),
            true);
    public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
                "value.object.column.bitmask.enabled.ru.hmel.model.PositionType"),
            true);
    public static long UUID_COLUMN_BITMASK = 1L;
    public static long POSITION_ID_COLUMN_BITMASK = 2L;
    public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
                "lock.expiration.time.ru.hmel.model.PositionType"));
    private static ClassLoader _classLoader = PositionType.class.getClassLoader();
    private static Class<?>[] _escapedModelInterfaces = new Class[] {
            PositionType.class
        };
    private String _uuid;
    private String _originalUuid;
    private long _position_id;
    private String _name;
    private long _columnBitmask;
    private PositionType _escapedModel;

    public PositionTypeModelImpl() {
    }

    /**
     * Converts the soap model instance into a normal model instance.
     *
     * @param soapModel the soap model instance to convert
     * @return the normal model instance
     */
    public static PositionType toModel(PositionTypeSoap soapModel) {
        if (soapModel == null) {
            return null;
        }

        PositionType model = new PositionTypeImpl();

        model.setUuid(soapModel.getUuid());
        model.setPosition_id(soapModel.getPosition_id());
        model.setName(soapModel.getName());

        return model;
    }

    /**
     * Converts the soap model instances into normal model instances.
     *
     * @param soapModels the soap model instances to convert
     * @return the normal model instances
     */
    public static List<PositionType> toModels(PositionTypeSoap[] soapModels) {
        if (soapModels == null) {
            return null;
        }

        List<PositionType> models = new ArrayList<PositionType>(soapModels.length);

        for (PositionTypeSoap soapModel : soapModels) {
            models.add(toModel(soapModel));
        }

        return models;
    }

    @Override
    public long getPrimaryKey() {
        return _position_id;
    }

    @Override
    public void setPrimaryKey(long primaryKey) {
        setPosition_id(primaryKey);
    }

    @Override
    public Serializable getPrimaryKeyObj() {
        return _position_id;
    }

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj) {
        setPrimaryKey(((Long) primaryKeyObj).longValue());
    }

    @Override
    public Class<?> getModelClass() {
        return PositionType.class;
    }

    @Override
    public String getModelClassName() {
        return PositionType.class.getName();
    }

    @Override
    public Map<String, Object> getModelAttributes() {
        Map<String, Object> attributes = new HashMap<String, Object>();

        attributes.put("uuid", getUuid());
        attributes.put("position_id", getPosition_id());
        attributes.put("name", getName());

        return attributes;
    }

    @Override
    public void setModelAttributes(Map<String, Object> attributes) {
        String uuid = (String) attributes.get("uuid");

        if (uuid != null) {
            setUuid(uuid);
        }

        Long position_id = (Long) attributes.get("position_id");

        if (position_id != null) {
            setPosition_id(position_id);
        }

        String name = (String) attributes.get("name");

        if (name != null) {
            setName(name);
        }
    }

    @JSON
    @Override
    public String getUuid() {
        if (_uuid == null) {
            return StringPool.BLANK;
        } else {
            return _uuid;
        }
    }

    @Override
    public void setUuid(String uuid) {
        if (_originalUuid == null) {
            _originalUuid = _uuid;
        }

        _uuid = uuid;
    }

    public String getOriginalUuid() {
        return GetterUtil.getString(_originalUuid);
    }

    @JSON
    @Override
    public long getPosition_id() {
        return _position_id;
    }

    @Override
    public void setPosition_id(long position_id) {
        _position_id = position_id;
    }

    @JSON
    @Override
    public String getName() {
        if (_name == null) {
            return StringPool.BLANK;
        } else {
            return _name;
        }
    }

    @Override
    public void setName(String name) {
        _name = name;
    }

    public long getColumnBitmask() {
        return _columnBitmask;
    }

    @Override
    public ExpandoBridge getExpandoBridge() {
        return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
            PositionType.class.getName(), getPrimaryKey());
    }

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
        ExpandoBridge expandoBridge = getExpandoBridge();

        expandoBridge.setAttributes(serviceContext);
    }

    @Override
    public PositionType toEscapedModel() {
        if (_escapedModel == null) {
            _escapedModel = (PositionType) ProxyUtil.newProxyInstance(_classLoader,
                    _escapedModelInterfaces, new AutoEscapeBeanHandler(this));
        }

        return _escapedModel;
    }

    @Override
    public Object clone() {
        PositionTypeImpl positionTypeImpl = new PositionTypeImpl();

        positionTypeImpl.setUuid(getUuid());
        positionTypeImpl.setPosition_id(getPosition_id());
        positionTypeImpl.setName(getName());

        positionTypeImpl.resetOriginalValues();

        return positionTypeImpl;
    }

    @Override
    public int compareTo(PositionType positionType) {
        long primaryKey = positionType.getPrimaryKey();

        if (getPrimaryKey() < primaryKey) {
            return -1;
        } else if (getPrimaryKey() > primaryKey) {
            return 1;
        } else {
            return 0;
        }
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }

        if (!(obj instanceof PositionType)) {
            return false;
        }

        PositionType positionType = (PositionType) obj;

        long primaryKey = positionType.getPrimaryKey();

        if (getPrimaryKey() == primaryKey) {
            return true;
        } else {
            return false;
        }
    }

    @Override
    public int hashCode() {
        return (int) getPrimaryKey();
    }

    @Override
    public void resetOriginalValues() {
        PositionTypeModelImpl positionTypeModelImpl = this;

        positionTypeModelImpl._originalUuid = positionTypeModelImpl._uuid;

        positionTypeModelImpl._columnBitmask = 0;
    }

    @Override
    public CacheModel<PositionType> toCacheModel() {
        PositionTypeCacheModel positionTypeCacheModel = new PositionTypeCacheModel();

        positionTypeCacheModel.uuid = getUuid();

        String uuid = positionTypeCacheModel.uuid;

        if ((uuid != null) && (uuid.length() == 0)) {
            positionTypeCacheModel.uuid = null;
        }

        positionTypeCacheModel.position_id = getPosition_id();

        positionTypeCacheModel.name = getName();

        String name = positionTypeCacheModel.name;

        if ((name != null) && (name.length() == 0)) {
            positionTypeCacheModel.name = null;
        }

        return positionTypeCacheModel;
    }

    @Override
    public String toString() {
        StringBundler sb = new StringBundler(7);

        sb.append("{uuid=");
        sb.append(getUuid());
        sb.append(", position_id=");
        sb.append(getPosition_id());
        sb.append(", name=");
        sb.append(getName());
        sb.append("}");

        return sb.toString();
    }

    @Override
    public String toXmlString() {
        StringBundler sb = new StringBundler(13);

        sb.append("<model><model-name>");
        sb.append("ru.hmel.model.PositionType");
        sb.append("</model-name>");

        sb.append(
            "<column><column-name>uuid</column-name><column-value><![CDATA[");
        sb.append(getUuid());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>position_id</column-name><column-value><![CDATA[");
        sb.append(getPosition_id());
        sb.append("]]></column-value></column>");
        sb.append(
            "<column><column-name>name</column-name><column-value><![CDATA[");
        sb.append(getName());
        sb.append("]]></column-value></column>");

        sb.append("</model>");

        return sb.toString();
    }
}
