package ru.hmel.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the ElectroType service. Represents a row in the &quot;store_ElectroType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ru.hmel.model.impl.ElectroTypeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ru.hmel.model.impl.ElectroTypeImpl}.
 * </p>
 *
 * @author Hmel Max
 * @see ElectroType
 * @see ru.hmel.model.impl.ElectroTypeImpl
 * @see ru.hmel.model.impl.ElectroTypeModelImpl
 * @generated
 */
public interface ElectroTypeModel extends BaseModel<ElectroType> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a electro type model instance should use the {@link ElectroType} interface instead.
     */

    /**
     * Returns the primary key of this electro type.
     *
     * @return the primary key of this electro type
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this electro type.
     *
     * @param primaryKey the primary key of this electro type
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the electro_type_id of this electro type.
     *
     * @return the electro_type_id of this electro type
     */
    public long getElectro_type_id();

    /**
     * Sets the electro_type_id of this electro type.
     *
     * @param electro_type_id the electro_type_id of this electro type
     */
    public void setElectro_type_id(long electro_type_id);

    /**
     * Returns the name of this electro type.
     *
     * @return the name of this electro type
     */
    @AutoEscape
    public String getName();

    /**
     * Sets the name of this electro type.
     *
     * @param name the name of this electro type
     */
    public void setName(String name);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(ru.hmel.model.ElectroType electroType);

    @Override
    public int hashCode();

    @Override
    public CacheModel<ru.hmel.model.ElectroType> toCacheModel();

    @Override
    public ru.hmel.model.ElectroType toEscapedModel();

    @Override
    public ru.hmel.model.ElectroType toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
