package ru.hmel.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Employee service. Represents a row in the &quot;store_Employee&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ru.hmel.model.impl.EmployeeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ru.hmel.model.impl.EmployeeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Employee
 * @see ru.hmel.model.impl.EmployeeImpl
 * @see ru.hmel.model.impl.EmployeeModelImpl
 * @generated
 */
public interface EmployeeModel extends BaseModel<Employee> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a employee model instance should use the {@link Employee} interface instead.
     */

    /**
     * Returns the primary key of this employee.
     *
     * @return the primary key of this employee
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this employee.
     *
     * @param primaryKey the primary key of this employee
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the uuid of this employee.
     *
     * @return the uuid of this employee
     */
    @AutoEscape
    public String getUuid();

    /**
     * Sets the uuid of this employee.
     *
     * @param uuid the uuid of this employee
     */
    public void setUuid(String uuid);

    /**
     * Returns the employee_id of this employee.
     *
     * @return the employee_id of this employee
     */
    public long getEmployee_id();

    /**
     * Sets the employee_id of this employee.
     *
     * @param employee_id the employee_id of this employee
     */
    public void setEmployee_id(long employee_id);

    /**
     * Returns the lastname of this employee.
     *
     * @return the lastname of this employee
     */
    @AutoEscape
    public String getLastname();

    /**
     * Sets the lastname of this employee.
     *
     * @param lastname the lastname of this employee
     */
    public void setLastname(String lastname);

    /**
     * Returns the firstname of this employee.
     *
     * @return the firstname of this employee
     */
    @AutoEscape
    public String getFirstname();

    /**
     * Sets the firstname of this employee.
     *
     * @param firstname the firstname of this employee
     */
    public void setFirstname(String firstname);

    /**
     * Returns the patronymic of this employee.
     *
     * @return the patronymic of this employee
     */
    @AutoEscape
    public String getPatronymic();

    /**
     * Sets the patronymic of this employee.
     *
     * @param patronymic the patronymic of this employee
     */
    public void setPatronymic(String patronymic);

    /**
     * Returns the birthdate of this employee.
     *
     * @return the birthdate of this employee
     */
    public Date getBirthdate();

    /**
     * Sets the birthdate of this employee.
     *
     * @param birthdate the birthdate of this employee
     */
    public void setBirthdate(Date birthdate);

    /**
     * Returns the position of this employee.
     *
     * @return the position of this employee
     */
    public long getPosition();

    /**
     * Sets the position of this employee.
     *
     * @param position the position of this employee
     */
    public void setPosition(long position);

    /**
     * Returns the gender of this employee.
     *
     * @return the gender of this employee
     */
    public boolean getGender();

    /**
     * Returns <code>true</code> if this employee is gender.
     *
     * @return <code>true</code> if this employee is gender; <code>false</code> otherwise
     */
    public boolean isGender();

    /**
     * Sets whether this employee is gender.
     *
     * @param gender the gender of this employee
     */
    public void setGender(boolean gender);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(ru.hmel.model.Employee employee);

    @Override
    public int hashCode();

    @Override
    public CacheModel<ru.hmel.model.Employee> toCacheModel();

    @Override
    public ru.hmel.model.Employee toEscapedModel();

    @Override
    public ru.hmel.model.Employee toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
