package ru.hmel.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the PositionType service. Represents a row in the &quot;store_PositionType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ru.hmel.model.impl.PositionTypeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ru.hmel.model.impl.PositionTypeImpl}.
 * </p>
 *
 * @author Hmel Max
 * @see PositionType
 * @see ru.hmel.model.impl.PositionTypeImpl
 * @see ru.hmel.model.impl.PositionTypeModelImpl
 * @generated
 */
public interface PositionTypeModel extends BaseModel<PositionType> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a position type model instance should use the {@link PositionType} interface instead.
     */

    /**
     * Returns the primary key of this position type.
     *
     * @return the primary key of this position type
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this position type.
     *
     * @param primaryKey the primary key of this position type
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the position_id of this position type.
     *
     * @return the position_id of this position type
     */
    public long getPosition_id();

    /**
     * Sets the position_id of this position type.
     *
     * @param position_id the position_id of this position type
     */
    public void setPosition_id(long position_id);

    /**
     * Returns the name of this position type.
     *
     * @return the name of this position type
     */
    @AutoEscape
    public String getName();

    /**
     * Sets the name of this position type.
     *
     * @param name the name of this position type
     */
    public void setName(String name);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(ru.hmel.model.PositionType positionType);

    @Override
    public int hashCode();

    @Override
    public CacheModel<ru.hmel.model.PositionType> toCacheModel();

    @Override
    public ru.hmel.model.PositionType toEscapedModel();

    @Override
    public ru.hmel.model.PositionType toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
