package ru.hmel.model;

import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Purchase service. Represents a row in the &quot;store_Purchase&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ru.hmel.model.impl.PurchaseModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ru.hmel.model.impl.PurchaseImpl}.
 * </p>
 *
 * @author Hmel Max
 * @see Purchase
 * @see ru.hmel.model.impl.PurchaseImpl
 * @see ru.hmel.model.impl.PurchaseModelImpl
 * @generated
 */
public interface PurchaseModel extends BaseModel<Purchase> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a purchase model instance should use the {@link Purchase} interface instead.
     */

    /**
     * Returns the primary key of this purchase.
     *
     * @return the primary key of this purchase
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this purchase.
     *
     * @param primaryKey the primary key of this purchase
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the purchase_id of this purchase.
     *
     * @return the purchase_id of this purchase
     */
    public long getPurchase_id();

    /**
     * Sets the purchase_id of this purchase.
     *
     * @param purchase_id the purchase_id of this purchase
     */
    public void setPurchase_id(long purchase_id);

    /**
     * Returns the electro_id of this purchase.
     *
     * @return the electro_id of this purchase
     */
    public long getElectro_id();

    /**
     * Sets the electro_id of this purchase.
     *
     * @param electro_id the electro_id of this purchase
     */
    public void setElectro_id(long electro_id);

    /**
     * Returns the employee_id of this purchase.
     *
     * @return the employee_id of this purchase
     */
    public long getEmployee_id();

    /**
     * Sets the employee_id of this purchase.
     *
     * @param employee_id the employee_id of this purchase
     */
    public void setEmployee_id(long employee_id);

    /**
     * Returns the purchase date of this purchase.
     *
     * @return the purchase date of this purchase
     */
    public Date getPurchaseDate();

    /**
     * Sets the purchase date of this purchase.
     *
     * @param purchaseDate the purchase date of this purchase
     */
    public void setPurchaseDate(Date purchaseDate);

    /**
     * Returns the type of this purchase.
     *
     * @return the type of this purchase
     */
    public long getType();

    /**
     * Sets the type of this purchase.
     *
     * @param type the type of this purchase
     */
    public void setType(long type);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(ru.hmel.model.Purchase purchase);

    @Override
    public int hashCode();

    @Override
    public CacheModel<ru.hmel.model.Purchase> toCacheModel();

    @Override
    public ru.hmel.model.Purchase toEscapedModel();

    @Override
    public ru.hmel.model.Purchase toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
