package ru.hmel.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the ElectroEmployee service. Represents a row in the &quot;store_ElectroEmployee&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ru.hmel.model.impl.ElectroEmployeeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ru.hmel.model.impl.ElectroEmployeeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ElectroEmployee
 * @see ru.hmel.model.impl.ElectroEmployeeImpl
 * @see ru.hmel.model.impl.ElectroEmployeeModelImpl
 * @generated
 */
public interface ElectroEmployeeModel extends BaseModel<ElectroEmployee> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a electro employee model instance should use the {@link ElectroEmployee} interface instead.
     */

    /**
     * Returns the primary key of this electro employee.
     *
     * @return the primary key of this electro employee
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this electro employee.
     *
     * @param primaryKey the primary key of this electro employee
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the uuid of this electro employee.
     *
     * @return the uuid of this electro employee
     */
    @AutoEscape
    public String getUuid();

    /**
     * Sets the uuid of this electro employee.
     *
     * @param uuid the uuid of this electro employee
     */
    public void setUuid(String uuid);

    /**
     * Returns the electro_employee_id of this electro employee.
     *
     * @return the electro_employee_id of this electro employee
     */
    public long getElectro_employee_id();

    /**
     * Sets the electro_employee_id of this electro employee.
     *
     * @param electro_employee_id the electro_employee_id of this electro employee
     */
    public void setElectro_employee_id(long electro_employee_id);

    /**
     * Returns the etype of this electro employee.
     *
     * @return the etype of this electro employee
     */
    public long getEtype();

    /**
     * Sets the etype of this electro employee.
     *
     * @param etype the etype of this electro employee
     */
    public void setEtype(long etype);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(ru.hmel.model.ElectroEmployee electroEmployee);

    @Override
    public int hashCode();

    @Override
    public CacheModel<ru.hmel.model.ElectroEmployee> toCacheModel();

    @Override
    public ru.hmel.model.ElectroEmployee toEscapedModel();

    @Override
    public ru.hmel.model.ElectroEmployee toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
