package ru.hmel.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the PurchaseType service. Represents a row in the &quot;store_PurchaseType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link ru.hmel.model.impl.PurchaseTypeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ru.hmel.model.impl.PurchaseTypeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PurchaseType
 * @see ru.hmel.model.impl.PurchaseTypeImpl
 * @see ru.hmel.model.impl.PurchaseTypeModelImpl
 * @generated
 */
public interface PurchaseTypeModel extends BaseModel<PurchaseType> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a purchase type model instance should use the {@link PurchaseType} interface instead.
     */

    /**
     * Returns the primary key of this purchase type.
     *
     * @return the primary key of this purchase type
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this purchase type.
     *
     * @param primaryKey the primary key of this purchase type
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the uuid of this purchase type.
     *
     * @return the uuid of this purchase type
     */
    @AutoEscape
    public String getUuid();

    /**
     * Sets the uuid of this purchase type.
     *
     * @param uuid the uuid of this purchase type
     */
    public void setUuid(String uuid);

    /**
     * Returns the purchase_type_id of this purchase type.
     *
     * @return the purchase_type_id of this purchase type
     */
    public long getPurchase_type_id();

    /**
     * Sets the purchase_type_id of this purchase type.
     *
     * @param purchase_type_id the purchase_type_id of this purchase type
     */
    public void setPurchase_type_id(long purchase_type_id);

    /**
     * Returns the name of this purchase type.
     *
     * @return the name of this purchase type
     */
    @AutoEscape
    public String getName();

    /**
     * Sets the name of this purchase type.
     *
     * @param name the name of this purchase type
     */
    public void setName(String name);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(ru.hmel.model.PurchaseType purchaseType);

    @Override
    public int hashCode();

    @Override
    public CacheModel<ru.hmel.model.PurchaseType> toCacheModel();

    @Override
    public ru.hmel.model.PurchaseType toEscapedModel();

    @Override
    public ru.hmel.model.PurchaseType toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
